### ISSUE TITLE
WARNING: Could not parse n transform function.

### ISSUE THREAD

**Issue by PatrykPatryk5** [distubejs/ytdl-core#22]
## Describe the bug
I have no idea what happened. I didn't change anything and it broke

WARNING: Could not parse n transform function.
Please report this issue with the "1720463648608-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.
## File
[1720463648608-base.zip](https://github.com/user-attachments/files/16133358/1720463648608-base.zip)

## Environment

- @distube/ytdl-core version: 4.13.4
- Node.js version: 21.7.3
- Operating system: Linux 5.15.104-1-pve

**Comment by Landjager** [comment]
i have the same error on windows 11 right now. Sometimes it works, sometimes not.

**Comment by yagizza** [comment]
i got the same issue aswell. it was fine until this morning. i didnt change anything either but bot disconnects immediately after joining vc and gives this error.

**Comment by vitor-kb** [comment]
Same here, tried npm update or reinstalling ytdl-core, still nothing

**Comment by mamdouhaass** [comment]
anyone what should i do to make it work??

**Comment by execaman** [comment]
switch to soundcloud for now, youtube is being strict even after having cookies this time

**Comment by ryokr** [comment]
youtube cooked

**Comment by AVAT1010** [comment]
Same error anyone figureout?

**Comment by mamdouhaass** [comment]
Will it be resolved?

**Comment by soya-daizu** [comment]
here's the patch: https://github.com/soya-daizu/ytdl-core/tree/sig-patch

**Comment by mamdouhaass** [comment]
@soya-daizu can u tell us how to do it?

**Comment by mamdouhaass** [comment]
@soya-daizu should i just copy your package.json and copy it to my code?

**Comment by soya-daizu** [comment]
@mamdouhaass Yes you can just replace it and it should work. However, I'm not going to update this further, so you should put it back as it used to be when it's fixed in this repo.

**Comment by mamdouhaass** [comment]
U will not fix it for good? @soya-daizu

**Comment by omerman** [comment]
> here's the patch until it's fixed in the upstream https://github.com/soya-daizu/ytdl-core/tree/sig-patch
> 
> package.json: `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"`

@soya-daizu Thank you so much. appreciate you ❤️

**Comment by soya-daizu** [comment]
@mamdouhaass It should work until youtube breaks it again. It's just that this branch will not be maintained in parallel to the original one.

**Comment by vitor-kb** [comment]
> Here's the patch until it's fixed in the upstream https://github.com/soya-daizu/ytdl-core/tree/sig-patch
> 
> package.json: `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"`
> 
> note: This is essentially just copying Lavalink's patch [lavalink-devs/youtube-source@7103b1a](https://github.com/lavalink-devs/youtube-source/commit/7103b1a14cd8731d2fa1e0b401253443f7358f68)

It worked!

**Comment by mamdouhaass** [comment]
@vitor-kb bro can u tell me what u did?

**Comment by mamdouhaass** [comment]
what should i copy from the patch?

**Comment by smclean117** [comment]
> Here's the patch until it's fixed in the upstream https://github.com/soya-daizu/ytdl-core/tree/sig-patch
> 
> package.json: `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"`
> 
> note: This is essentially just copying Lavalink's patch [lavalink-devs/youtube-source@7103b1a](https://github.com/lavalink-devs/youtube-source/commit/7103b1a14cd8731d2fa1e0b401253443f7358f68)

Thank you, saved the day.

**Comment by mamdouhaass** [comment]
@smclean117 can u tell me what to do?

**Comment by Seukoooowwdd** [comment]
Help 

WARNING: Could not parse n transform function.
Please report this issue with the "1720559747647-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.

**Comment by Seukoooowwdd** [comment]
@smclean117 I need help please

**Comment by smclean117** [comment]
> @smclean117 can u tell me what to do?

I'm a relative rookie when it comes to this but I replaced ytdl-core line in package.json with the line `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"` deleted ytdl-core from node_modules folder then ran npm install again

**Comment by mamdouhaass** [comment]
i have more than one line in package.json called ytdl @smclean117

**Comment by smclean117** [comment]
```
"dependencies": {
    "@discord-player/extractor": "^4.4.1",
    "@discordjs/opus": "^0.9.0",
    "conf": "^12.0.0",
    "discord-player": "^6.6.2",
    "discord.js": "^14.12.1",
    "dotenv": "^16.3.1",
    "ffmpeg": "0.0.4",
    "fluent-ffmpeg": "^2.1.2",
    "opusscript": "0.0.8",
    "prism-media": "^1.3.5",
    "@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"
  },

```

this is my dependencies section if that helps

**Comment by Seukoooowwdd** [comment]
@smclean117 
I did what you said to do and when I do npm install I get this error


PS C:\Users\conta\OneDrive\Desktop\> npm install
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\conta\AppData\Local\npm-cache\_logs\2024-07-09T21_29_36_194Z-debug-0.log

**Comment by smclean117** [comment]
> @smclean117 I did what you said to do and when I do npm install I get this error
> 
> PS C:\Users\conta\OneDrive\Desktop> npm install npm ERR! code ENOENT npm ERR! syscall spawn git npm ERR! path git npm ERR! errno -4058 npm ERR! enoent An unknown git error occurred npm ERR! enoent This is related to npm not being able to find a file. npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\conta\AppData\Local\npm-cache_logs\2024-07-09T21_29_36_194Z-debug-0.log

I'm not sure i can help here sorry, maybe you formatted the line incorrectly due to it not being able to find the file? or git isnt installed on your machine correctly.

be aware we will all use this package in different ways and in different implementations so what i did may not be relevant to you, for example mine is a discord bot installed on Raspberry Pi OS.

**Comment by soya-daizu** [comment]
@Seukoooowwdd
What you should have done is to replace only one line which defines the dependency to this package (`@distube/ytdl-core`)
Revert your changes and find the line that starts with `"@distube/ytdl-core": `. That should look like `"@distube/ytdl-core": "^4.13.4"` or something.
Now replace that line with `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"` and run `npm install` again.

**Comment by soya-daizu** [comment]
@mamdouhaass ^This is essentially what you also need to do

**Comment by Seukoooowwdd** [comment]
@soya-daizuShould I do that? Because that's what I did and when I do npm install I get an error I think there is something I didn't do that needed to be done

**Comment by mamdouhaass** [comment]
@soya-daizu thats what i did when i run npm i i get this error 
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\Administrator\AppData\Local\npm-cache\_logs\2024-07-09T21_42_29_535Z-debug-0.log

**Comment by mamdouhaass** [comment]
should i change the package.lock json? too?

**Comment by soya-daizu** [comment]
@mamdouhaass I think you don't have git installed on your system and that's causing the problem.

**Comment by Seukoooowwdd** [comment]
@soya-daizu How to install git?

**Comment by mamdouhaass** [comment]
how to do that?

**Comment by mamdouhaass** [comment]
i installed git windows same problem

**Comment by smclean117** [comment]
> i installed git windows same problem

what does running `git --version` state?

**Comment by Seukoooowwdd** [comment]
It's good for me but when I start the music it disconnects straight away

**Comment by mamdouhaass** [comment]
mine doesnt disconnect it create a new js file with numbers

**Comment by mamdouhaass** [comment]
what did u install @Seukoooowwdd

**Comment by Seukoooowwdd** [comment]
Thank you, it's all good for me, will the problem come back one day or not or is it good? @soya-daizu

**Comment by soya-daizu** [comment]
@Seukoooowwdd I don't know. This will be the permanent fix for this specific problem, but if youtube decides to break things again then people need to find another workaround. Until then it will just happen to work and that's always how downloading from youtube has been. I guess it will be okay for a couple of months or so.

**Comment by vitor-kb** [comment]
> @vitor-kb bro can u tell me what u did?
> 
> 

Updated package.json and run npm i again

**Comment by Seukoooowwdd** [comment]
What should I do when I have this?
WARNING: Using old cookie format, please use the new one instead. (https://github.com/distubejs/ytdl-core#cookies-support)

**Comment by 4uuc** [comment]
What should I change? The problem is not solved. Please help me ?

{
  "name": "ytdl-core",
  "description": "YouTube video downloader in pure javascript.",
  "keywords": [
    "youtube",
    "video",
    "download"
  ],
  "version": "4.11.5",
  "repository": {
    "type": "git",
    "url": "git://github.com/fent/node-ytdl-core.git"
  },
  "author": "fent <fentbox@gmail.com> (https://github.com/fent)",
  "contributors": [
    "Tobias Kutscha (https://github.com/TimeForANinja)",
    "Andrew Kelley (https://github.com/andrewrk)",
    "Mauricio Allende (https://github.com/mallendeo)",
    "Rodrigo Altamirano (https://github.com/raltamirano)",
    "Jim Buck (https://github.com/JimmyBoh)",
    "Paweł Ruciński (https://github.com/Roki100)",
    "Alexander Paolini (https://github.com/Million900o)"
  ],
  "main": "./lib/index.js",
  "types": "./typings/index.d.ts",
  "files": [
    "lib",
    "typings"
  ],
  "scripts": {
    "test": "nyc --reporter=lcov --reporter=text-summary npm run test:unit",
    "test:unit": "mocha --ignore test/irl-test.js test/*-test.js --timeout 4000",
    "test:irl": "mocha --timeout 16000 test/irl-test.js",
    "lint": "eslint ./",
    "lint:fix": "eslint --fix ./",
    "lint:typings": "tslint typings/index.d.ts",
    "lint:typings:fix": "tslint --fix typings/index.d.ts"
  },
  "dependencies": {
    "m3u8stream": "^0.8.6",
    "miniget": "^4.2.2",
    "sax": "^1.1.3"
  },
  "devDependencies": {
    "@types/node": "^13.1.0",
    "assert-diff": "^3.0.1",
    "dtslint": "^3.6.14",
    "eslint": "^6.8.0",
    "mocha": "^7.0.0",
    "muk-require": "^1.2.0",
    "nock": "^13.0.4",
    "nyc": "^15.0.0",
    "sinon": "^9.0.0",
    "stream-equal": "~1.1.0",
    "typescript": "^3.9.7"
  },
  "engines": {
    "node": ">=12"
  },
  "license": "MIT"
}

**Comment by asssaaa21** [comment]
> @Seukoooowwdd What you should have done is to replace only one line which defines the dependency to this package (`@distube/ytdl-core`) Revert your changes and find the line that starts with `"@distube/ytdl-core": `. That should look like `"@distube/ytdl-core": "^4.13.4"` or something. Now replace that line with `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"` and run `npm install` again.
> 
> Notice that you're changing the source of `@distube/ytdl-core` to my branch. Once this problem is also fixed on the original branch, you should put it back to the original or you won't receive future updates to this package.

i did exacly like your method, used it in my file and everything, yet bot when playing song joins and everything is okay, issue only does not play any song, even tried to sudo apt-get ffmpeg and update phyton also, sometimes it makes the problem for that too, but as i can see this time its not ffmpeg its actually tydl-core issue, and yet your method isn't working also bot keeps leaving the voice channel after joinning..

**Comment by ryokr** [comment]
"dependencies": {
      "@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch",
},

```"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch",```

Just simply replace ` "@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"`  at the line started with  ` "@distube/ytdl-core"` in your package.json.

Then run npm i. If it still warning, remove `node_module`, `package.json` completely, run npm i agian.

It worked for me

**Comment by ryokr** [comment]
"dependencies": {

     "@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch",

},

Just simply replace `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"`  at the line started with  ` "@distube/ytdl-core"` in your package.json.

Then run npm i. If it still warning, remove `node_module`, `package-lock.json` completely, run npm i again.

It worked for me.

**Comment by matthewmichel** [comment]
This is really interesting. The patch worked for me locally. When I deployed it it no longer is working and is still returning the 403/could not parse n transform function error. Any thoughts to why this would be happening?

**Comment by bagaspwibisono** [comment]
@matthewmichel have you delete .npm(if exist), node_modules & package_lock.json files and try run again npm i script?

**Comment by AlexInCube** [comment]
I am delete node_modules, pnpm-lock.yaml, execute "pnpm store prune", changed package to "@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch", execute "pnpm install". And i still get WARNING: Could not parse n transform function + Server returned 403 Forbidden (access denied). I tried to change cookies and remove cookies entirely. Nothing changed.

**Comment by brusnaclee** [comment]
> Here's the patch until it's fixed in the upstream https://github.com/soya-daizu/ytdl-core/tree/sig-patch
> 
> package.json: `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"`
> 
> note: This is essentially just copying Lavalink's patch [lavalink-devs/youtube-source@7103b1a](https://github.com/lavalink-devs/youtube-source/commit/7103b1a14cd8731d2fa1e0b401253443f7358f68)

Thank you it's worked

**Comment by Englard** [comment]
> Aquí está el parche hasta que se solucione en el upstream https://github.com/soya-daizu/ytdl-core/tree/sig-patch
> 
> paquete.json: `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"`
> 
> Nota: Esto es básicamente solo copiar el parche de Lavalink [lavalink-devs/youtube-source@ 7103b1a](https://github.com/lavalink-devs/youtube-source/commit/7103b1a14cd8731d2fa1e0b401253443f7358f68)




------------------------------
funcionó muchas gracias
------------------------------

it worked thank you very much

**Comment by datly** [comment]
> > Aquí está el parche hasta que se solucione en el upstream https://github.com/soya-daizu/ytdl-core/tree/sig-patch
> > paquete.json: `"@distube/ytdl-core": "github:soya-daizu/ytdl-core#sig-patch"`
> > Nota: Esto es básicamente solo copiar el parche de Lavalink [lavalink-devs/youtube-source@ 7103b1a](https://github.com/lavalink-devs/youtube-source/commit/7103b1a14cd8731d2fa1e0b401253443f7358f68)
> 
> ## funcionó muchas gracias
> it worked thank you very much

Hi bro, repo not found

**Comment by ybd-project-ver1** [comment]
Try this.
https://github.com/ybd-project-ver1/ytdl-core

**Comment by gabrieleforgheri** [comment]
how do i fix it if im running it on docker portainer?
