### ISSUE TITLE
Cannot destructure property 'jar' of 'options.agent' as it is undefined

### ISSUE THREAD

**Issue by Brainicism** [distubejs/ytdl-core#62]
## Describe the bug
`getInfo` calls are failing. Is passing an `agent` with cookies required now? Requiring this by default seems to be a pretty major breaking change, given that most people probably use this library unauthenticated. 

```
TypeError: Cannot destructure property 'jar' of 'options.agent' as it is undefined.
    at fetchIosJsonPlayer (/workspace/node_modules/@distube/ytdl-core/lib/info.js:320:11)
    at exports.getInfo (/workspace/node_modules/@distube/ytdl-core/lib/info.js:245:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)}
```

Seems introduced by https://github.com/distubejs/ytdl-core/commit/6ddf70d8d74ba73ea434dd085357989648340883

## Environment

- @distube/ytdl-core version: 4.14.0
- Node.js version: v18.20.3
- Operating system: Debian GNU/Linux 11

**Comment by skick1234** [comment]
It is included as a default option, but I cloned `options` object in `getBasicInfo` so it won't be passed to `getInfo` options. It should be resolved now.

**Comment by Brainicism** [comment]
Getting the same error but in a strange way. If I call `getBasicInfo()` or `getInfo()` independently, they will succeed. But if I call either of them one after the other, I still receive the same error as above. 

```
node ➜ /workspace (update-ytdl) $ npx ts-node src/ytdl-test.ts 
/workspace/node_modules/@distube/ytdl-core/lib/info.js:322
  const { jar, dispatcher } = options.agent;
          ^
TypeError: Cannot destructure property 'jar' of 'options.agent' as it is undefined.
    at fetchIosJsonPlayer (/workspace/node_modules/@distube/ytdl-core/lib/info.js:322:11)
    at exports.getInfo (/workspace/node_modules/@distube/ytdl-core/lib/info.js:247:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
    
```ts
    (async () => {
    const x = await ytdl.getBasicInfo(
        "http://www.youtube.com/watch?v=aqz-KE-bpKQ",
    );

    const y = await ytdl.getInfo("http://www.youtube.com/watch?v=aqz-KE-bpKQ");
})();

```
