### ISSUE TITLE
WARNING: Could not parse n transform function.

### ISSUE THREAD

**Issue by meassamrong** [distubejs/ytdl-core#7]
WARNING: Could not parse n transform function.
Please report this issue with the "xxxxxxxxxxxxxx-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.
[1690359871044-base.txt](https://github.com/distubejs/ytdl-core/files/12169745/1690359871044-base.txt)

**Comment by MimoCrew** [comment]
i got also the samy error

**Comment by MidSpike** [comment]
Same here:
[1690369713207-base.txt](https://github.com/distubejs/ytdl-core/files/12171645/1690369713207-base.txt)

**Comment by skick1234** [comment]
Fixed with e3444db4b7c78bebc35ac02e26456c4f3f67e009
Update to the latest version with `npm i @distube/ytdl-core@latest`

**Comment by MidSpike** [comment]
Not fixed it latest version, I got that in the latest version

**Comment by skick1234** [comment]
> Not fixed it latest version, I got that in the latest version

It is released 1 min ago, 4.11.17

**Comment by MidSpike** [comment]
Oh oops, sorry about that. I should really think before typing...

**Comment by skick1234** [comment]
Duplicated #4
